"""add_user_id_pk

Revision ID: c491db828a78
Revises: 0001
Create Date: 2026-04-26 09:17:53.308597

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c491db828a78'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create new eremek catalog table
    op.create_table('eremek',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nev', sa.String(length=128), nullable=False),
    sa.Column('leiras', sa.Text(), nullable=False),
    sa.Column('ikon', sa.String(length=16), nullable=False),
    sa.Column('kategoria', sa.String(length=32), nullable=False),
    sa.Column('ideiglenes', sa.Boolean(), nullable=False),
    sa.Column('ervenyes_napig', sa.Integer(), nullable=True),
    sa.Column('ismetelheto', sa.Boolean(), nullable=False),
    sa.Column('kep_url', sa.Text(), nullable=True),
    sa.Column('hang_url', sa.Text(), nullable=True),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('privat', sa.Boolean(), nullable=False),
    sa.Column('cel_felhasznalo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eremek', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eremek_cel_felhasznalo'), ['cel_felhasznalo'], unique=False)
        batch_op.create_index(batch_op.f('ix_eremek_kategoria'), ['kategoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_eremek_privat'), ['privat'], unique=False)

    # 2. Recreate felhasznalok with a proper INTEGER PK
    #    (SQLite cannot ALTER TABLE to change the primary key)
    op.execute("""
        CREATE TABLE felhasznalok_new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nev VARCHAR(64) NOT NULL,
            extra_info TEXT,
            created_at DATETIME NOT NULL
        )
    """)
    op.execute("""
        INSERT INTO felhasznalok_new (nev, extra_info, created_at)
            SELECT nev, NULL, COALESCE(created_at, datetime('now')) FROM felhasznalok
    """)
    op.execute("DROP TABLE felhasznalok")
    op.execute("ALTER TABLE felhasznalok_new RENAME TO felhasznalok")
    op.execute("CREATE UNIQUE INDEX ix_felhasznalok_nev ON felhasznalok (nev)")

    # 3. Add felhasznalo_id FK column to each child table
    with op.batch_alter_table('felhasznalo_eremek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('felhasznalo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_felhasznalo_eremek_felhasznalo_id'), ['felhasznalo_id'], unique=False)
        batch_op.create_foreign_key('fk_felhasznalo_eremek_felhasznalo_id', 'felhasznalok', ['felhasznalo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('interakciok', schema=None) as batch_op:
        batch_op.add_column(sa.Column('felhasznalo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_interakciok_felhasznalo_id'), ['felhasznalo_id'], unique=False)
        batch_op.create_foreign_key('fk_interakciok_felhasznalo_id', 'felhasznalok', ['felhasznalo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('megoldasok', schema=None) as batch_op:
        batch_op.add_column(sa.Column('felhasznalo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_megoldasok_felhasznalo_id'), ['felhasznalo_id'], unique=False)
        batch_op.create_foreign_key('fk_megoldasok_felhasznalo_id', 'felhasznalok', ['felhasznalo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('menetek', schema=None) as batch_op:
        batch_op.add_column(sa.Column('felhasznalo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_menetek_felhasznalo_id'), ['felhasznalo_id'], unique=False)
        batch_op.create_foreign_key('fk_menetek_felhasznalo_id', 'felhasznalok', ['felhasznalo_id'], ['id'], ondelete='CASCADE')

    # 4. Backfill felhasznalo_id from felhasznalo_nev lookup
    for table in ('menetek', 'megoldasok', 'interakciok', 'felhasznalo_eremek'):
        op.execute(f"""
            UPDATE {table}
            SET felhasznalo_id = (
                SELECT id FROM felhasznalok WHERE nev = {table}.felhasznalo_nev
            )
            WHERE felhasznalo_id IS NULL
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menetek', schema=None) as batch_op:
        batch_op.drop_constraint('fk_menetek_felhasznalo_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_menetek_felhasznalo_nev', 'felhasznalok', ['felhasznalo_nev'], ['nev'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_menetek_felhasznalo_id'))
        batch_op.drop_column('felhasznalo_id')

    with op.batch_alter_table('megoldasok', schema=None) as batch_op:
        batch_op.drop_constraint('fk_megoldasok_felhasznalo_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_megoldasok_felhasznalo_id'))
        batch_op.drop_column('felhasznalo_id')

    with op.batch_alter_table('interakciok', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interakciok_felhasznalo_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_interakciok_felhasznalo_id'))
        batch_op.drop_column('felhasznalo_id')

    with op.batch_alter_table('felhasznalok', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_felhasznalok_nev'))
        batch_op.drop_column('extra_info')
        batch_op.drop_column('id')

    with op.batch_alter_table('felhasznalo_eremek', schema=None) as batch_op:
        batch_op.drop_constraint('fk_felhasznalo_eremek_felhasznalo_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_felhasznalo_eremek_felhasznalo_id'))
        batch_op.drop_column('felhasznalo_id')

    with op.batch_alter_table('eremek', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eremek_privat'))
        batch_op.drop_index(batch_op.f('ix_eremek_kategoria'))
        batch_op.drop_index(batch_op.f('ix_eremek_cel_felhasznalo'))

    op.drop_table('eremek')
    # ### end Alembic commands ###
